// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { Skill } from '../types'
import { TemporalMapperInput, TemporalMapperOutput } from './schemas'
import { temporalMapperLogic } from './logic'
import { registerSkill } from '../registry'

export const temporalMapperSkill: Skill = {
  name: 'temporal_mapper',
  description: 'Maps date and time fields from FPML to CDM temporal structures. Handles trade dates, lifecycle dates, exercise dates, calculation periods, payment schedules, and valuation dates.',
  inputSchema: TemporalMapperInput,
  outputSchema: TemporalMapperOutput,
  fn: input => {
    const output = temporalMapperLogic(input)
    return {
      ...output,
      meaning: output.meaning ?? 'temporal-field-mapping',
      dateKind: output.dateKind ?? output.dateType,
      economicCategory: output.economicCategory ?? 'temporal',
      ambiguityFlags:
        output.confidence < 70
          ? [...(output.ambiguityFlags ?? []), 'temporal_mapping_needs_review']
          : output.ambiguityFlags,
      inferenceBasis: output.inferenceBasis ?? 'temporal_mapper_rule_set',
      patternSource: output.patternSource ?? 'fpml_temporal_patterns',
      confidenceRationale:
        output.confidenceRationale ??
        `Derived from temporal field heuristics with confidence ${output.confidence}.`,
    }
  },
  triggers: {
    keywords: [
      'date',
      'time',
      'expiration',
      'maturity',
      'effective',
      'termination',
      'payment',
      'settlement',
      'valuation',
      'pricing',
      'reset',
      'fixing',
      'calculation'
    ],
    fieldTypes: [
      'date',
      'dateTime',
      'xsd:date',
      'xsd:dateTime'
    ],
    patterns: [
      /.*[Dd]ate.*/,
      /.*[Tt]ime.*/
    ]
  }
}

// Auto-register on import
registerSkill(temporalMapperSkill)
