// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17
//
// INSTRUCTIONS FOR USER REVIEW:
// 1. Search for "TODO:" comments - these need domain expertise
// 2. Verify date field mappings match your institution's usage
// 3. Add any missing date fields specific to your products
// 4. Test date parsing with real FPML files

import type { TemporalMapperInput, TemporalMapperOutput } from './schemas'

/**
 * Temporal Mapper Logic
 *
 * SCHEMA ANALYSIS:
 * - FPML date fields: tradeDate, effectiveDate, terminationDate, expirationDate, etc.
 * - CDM date types: Date, AdjustableOrRelativeDate, CalculationPeriodDates, PaymentDates
 * - FPML supports: unadjustedDate + dateAdjustments, relativeDate references
 * - CDM normalizes to: single date format with adjustment rules
 *
 * DATE CATEGORIES:
 * 1. Trade dates: tradeDate (when trade executed)
 * 2. Lifecycle dates: effectiveDate, terminationDate, maturityDate
 * 3. Exercise dates: expirationDate, commencementDate (options)
 * 4. Calculation dates: calculationPeriodDates, resetDates, fixingDates
 * 5. Payment dates: paymentDates, settlementDate
 * 6. Valuation dates: valuationDate, pricingDate
 *
 * CONFIDENCE RULES:
 * - 95%: Direct field name match with standard naming
 * - 85%: Field name match with product-specific prefix
 * - 70%: Inferred from context (e.g., "date" in calculation context)
 */
export const temporalMapperLogic = (input: TemporalMapperInput): TemporalMapperOutput => {
  const lowerName = input.fieldName.toLowerCase()
  const path = input.fieldPath.toLowerCase()
  const contextStr = JSON.stringify(input.context || {}).toLowerCase()

  if (
    lowerName === 'creationtimestamp' ||
    lowerName === 'creation_timestamp' ||
    (path.includes('/header') && lowerName.includes('timestamp'))
  ) {
    return {
      cdmPath: 'packageMeta.fpmlHeader.creationTimestamp',
      transformation: 'map_fpml_creation_timestamp',
      confidence: path.includes('/header') ? 80 : 65,
      reasoning:
        'FPML creationTimestamp is document provenance (zoned dateTime), not an economic schedule date — stored under packageMeta.fpmlHeader.',
      dateType: 'document_timestamp',
    }
  }

  // ========================================
  // TRADE-LEVEL DATES (High Confidence)
  // ========================================

  // Trade date
  if (lowerName === 'tradedate' || lowerName === 'trade_date') {
    return {
      cdmPath: 'tradeDate',
      transformation: 'map_trade_date',
      confidence: 95,
      reasoning: 'Direct match: tradeDate → CDM tradeDate (date trade was executed)',
      dateType: 'trade_date'
    }
  }

  // Effective date (start date)
  if (lowerName === 'effectivedate' || lowerName === 'effective_date' ||
      lowerName === 'startdate' || lowerName === 'start_date') {
    return {
      cdmPath: 'economicTerms.effectiveDate',
      transformation: 'map_effective_date',
      confidence: 95,
      reasoning: 'Direct match: effectiveDate → CDM economicTerms.effectiveDate (when economic terms become effective)',
      dateType: 'effective_date',
      isAdjustable: true  // Typically has business day adjustments
    }
  }

  // Termination date (end date)
  if (lowerName === 'terminationdate' || lowerName === 'termination_date' ||
      lowerName === 'enddate' || lowerName === 'end_date' ||
      lowerName === 'maturitydate' || lowerName === 'maturity_date') {
    return {
      cdmPath: 'economicTerms.terminationDate',
      transformation: 'map_termination_date',
      confidence: 95,
      reasoning: 'Direct match: terminationDate/maturityDate → CDM economicTerms.terminationDate (when economic terms end)',
      dateType: 'termination_date',
      isAdjustable: true  // Typically has business day adjustments
    }
  }

  // ========================================
  // OPTION EXERCISE DATES
  // ========================================

  // Expiration date (options)
  if (lowerName.includes('expiration') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.exerciseTerms.expirationDate',
      transformation: 'map_expiration_date',
      confidence: 90,
      reasoning: 'Keyword match: expirationDate → CDM exerciseTerms.expirationDate (option expiration)',
      dateType: 'expiration_date'
    }
  }

  // Commencement date (American exercise)
  if (lowerName.includes('commencement') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.exerciseTerms.americanExercise.commencementDate',
      transformation: 'map_commencement_date',
      confidence: 90,
      reasoning: 'Keyword match: commencementDate → CDM americanExercise.commencementDate (start of exercise period)',
      dateType: 'effective_date'
    }
  }

  // ========================================
  // CALCULATION & PAYMENT DATES
  // ========================================

  // Calculation period dates (schedule)
  if (lowerName.includes('calculationperiod') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.calculationPeriodDates',
      transformation: 'map_calculation_period_dates',
      confidence: 95,
      reasoning: 'Keyword match: calculationPeriodDates → CDM calculationPeriodDates (schedule structure)',
      dateType: 'calculation_period',
      hasSchedule: true
    }
  }

  // Payment dates
  if (lowerName.includes('payment') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.paymentDates',
      transformation: 'map_payment_dates',
      confidence: 95,
      reasoning: 'Keyword match: paymentDate(s) → CDM paymentDates (payment schedule)',
      dateType: 'payment_date',
      hasSchedule: path.includes('paymentdates')  // plural = schedule
    }
  }

  // Reset dates (floating rate)
  if (lowerName.includes('reset') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.resetDates',
      transformation: 'map_reset_dates',
      confidence: 90,
      reasoning: 'Keyword match: resetDate(s) → CDM resetDates (rate reset schedule for floating legs)',
      dateType: 'reset_date',
      hasSchedule: true
    }
  }

  // Fixing dates
  if (lowerName.includes('fixing') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.resetDates.fixingDates',
      transformation: 'map_fixing_dates',
      confidence: 90,
      reasoning: 'Keyword match: fixingDate(s) → CDM resetDates.fixingDates (rate observation dates)',
      dateType: 'fixing_date',
      hasSchedule: true
    }
  }

  // ========================================
  // VALUATION & PRICING DATES
  // ========================================

  // Valuation date
  if (lowerName.includes('valuation') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.valuationDates',
      transformation: 'map_valuation_dates',
      confidence: 90,
      reasoning: 'Keyword match: valuationDate(s) → CDM valuationDates (asset valuation timing)',
      dateType: 'valuation_date'
    }
  }

  // Pricing date
  if (lowerName.includes('pricing') && lowerName.includes('date')) {
    return {
      cdmPath: 'payout.pricingDates',
      transformation: 'map_pricing_dates',
      confidence: 85,
      reasoning: 'Keyword match: pricingDate(s) → CDM pricingDates (commodity/asset pricing timing)',
      dateType: 'valuation_date',
      hasSchedule: true
    }
  }

  // Settlement date
  if (lowerName.includes('settlement') && lowerName.includes('date')) {
    return {
      cdmPath: 'settlementTerms.settlementDate',
      transformation: 'map_settlement_date',
      confidence: 90,
      reasoning: 'Keyword match: settlementDate → CDM settlementTerms.settlementDate (when settlement occurs)',
      dateType: 'payment_date'
    }
  }

  // ========================================
  // GENERIC DATE HANDLING
  // ========================================

  // Generic "date" field
  if (lowerName === 'date' || lowerName.endsWith('date')) {
    // TODO: Generic date fields need context to map correctly
    // Try to infer from parent element or path

    return {
      cdmPath: `unmapped.date.${input.fieldName}`,
      transformation: 'unknown_date_field',
      confidence: 40,
      reasoning: `Generic date field "${input.fieldName}" without clear context. Requires manual mapping based on parent element.`,
      dateType: 'unknown',
      todos: [
        'Check parent element to determine date purpose',
        'Map to appropriate CDM date field',
        'Determine if this is trade-level, payout-level, or schedule-level date'
      ]
    }
  }

  // Unadjusted date (child of adjustable date)
  if (lowerName === 'unadjusteddate' || lowerName === 'unadjusted_date') {
    return {
      cdmPath: 'parent.unadjustedDate',
      transformation: 'map_unadjusted_date',
      confidence: 85,
      reasoning: 'Component of AdjustableDate structure. Maps to parent date\'s unadjustedDate field.',
      dateType: 'effective_date',
      isAdjustable: true,
      todos: ['Determine parent element to construct full CDM path']
    }
  }

  // ========================================
  // NO MATCH
  // ========================================

  // Check if field type suggests it's a date
  if (input.fieldType?.toLowerCase().includes('date') ||
      input.fieldType?.toLowerCase().includes('time')) {
    return {
      cdmPath: `unmapped.temporal.${input.fieldName}`,
      transformation: 'unmapped_date_field',
      confidence: 30,
      reasoning: `Field type "${input.fieldType}" suggests temporal data, but field name "${input.fieldName}" doesn't match known patterns. Requires manual analysis.`,
      dateType: 'unknown',
      todos: ['Manually analyze this date field and define mapping rule']
    }
  }

  return {
    cdmPath: `unmapped.${input.fieldName}`,
    transformation: 'not_a_date_field',
    confidence: 0,
    reasoning: `Field "${input.fieldName}" does not match temporal field patterns.`,
    dateType: 'unknown'
  }
}
