// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import { z } from 'zod'
import { BaseSkillInput, BaseSkillOutput } from '../types'

/**
 * Input schema for temporal-mapper
 */
export const TemporalMapperInput = BaseSkillInput.extend({
  // No additional fields needed
})

/**
 * Output schema for temporal-mapper
 */
export const TemporalMapperOutput = BaseSkillOutput.extend({
  dateType: z.enum([
    'trade_date',
    'effective_date',
    'termination_date',
    'maturity_date',
    'expiration_date',
    'valuation_date',
    'payment_date',
    'reset_date',
    'fixing_date',
    'calculation_period',
    /** FPML document/header timestamps (provenance), not economic schedule dates */
    'document_timestamp',
    'unknown'
  ]),
  isAdjustable: z.boolean().optional(),      // Has business day adjustments
  isRelative: z.boolean().optional(),         // Relative date definition
  hasSchedule: z.boolean().optional()         // Part of a schedule/period
})

export type TemporalMapperInput = z.infer<typeof TemporalMapperInput>
export type TemporalMapperOutput = z.infer<typeof TemporalMapperOutput>
