// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { Skill } from '../types'
import { FloatingRateIndexResolverInput, FloatingRateIndexResolverOutput } from './schemas'
import { floatingRateIndexResolverLogic } from './logic'
import { registerSkill } from '../registry'

export const floatingRateIndexResolverSkill: Skill = {
  name: 'floating_rate_index_resolver',
  description: 'Maps floating rate indexes (LIBOR, EURIBOR, SOFR, SONIA, etc.) and tenors from FPML to CDM FloatingRateIndexEnum. Handles legacy IBOR rates and risk-free rates.',
  inputSchema: FloatingRateIndexResolverInput,
  outputSchema: FloatingRateIndexResolverOutput,
  fn: floatingRateIndexResolverLogic,
  triggers: {
    keywords: [
      'floatingrate',
      'index',
      'libor',
      'euribor',
      'sofr',
      'sonia',
      'estr',
      'tenor',
      'spread'
    ],
    patterns: [
      /.*[Ff]loating.*/,
      /.*[Ii]ndex.*/,
      /.*LIBOR.*/,
      /.*EURIBOR.*/,
      /.*SOFR.*/
    ]
  }
}

// Auto-register on import
registerSkill(floatingRateIndexResolverSkill)
