// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17
//
// INSTRUCTIONS FOR USER REVIEW:
// 1. Verify index name mappings match your institution's FPML conventions
// 2. Add any regional or exotic rate indexes
// 3. Confirm tenor parsing handles all period formats

import type { FloatingRateIndexResolverInput, FloatingRateIndexResolverOutput } from './schemas'

/**
 * Floating Rate Index Resolver Logic
 *
 * SCHEMA ANALYSIS:
 * - FPML uses compound index names: USD-LIBOR-BBA, EUR-EURIBOR-Reuters, GBP-SONIA-OIS
 * - CDM uses: FloatingRateIndexEnum (enumerated values)
 * - FPML tenor: <periodMultiplier>3</periodMultiplier><period>M</period>
 * - CDM tenor: Period { periodMultiplier: 3, period: M }
 *
 * INDEX CATEGORIES:
 * - LIBOR family: USD-LIBOR, GBP-LIBOR, JPY-LIBOR, CHF-LIBOR
 * - EURIBOR: EUR-EURIBOR-Reuters, EUR-EURIBOR-Telerate
 * - Risk-free rates: SOFR (USD), SONIA (GBP), ESTR (EUR), TONAR (JPY)
 * - Other: Prime rate, Fed Funds, TIBOR, HIBOR
 *
 * CONFIDENCE RULES:
 * - 95%: Exact index match (USD-LIBOR-BBA → FloatingRateIndexEnum.USD_LIBOR_BBA)
 * - 85%: Partial match with normalization (USD-LIBOR → USD_LIBOR)
 * - 70%: Generic floating rate without specific index
 */
export const floatingRateIndexResolverLogic = (
  input: FloatingRateIndexResolverInput
): FloatingRateIndexResolverOutput => {
  const lowerName = input.fieldName.toLowerCase()
  const indexName = (input.indexName || input.fieldValue || '').toUpperCase()

  // ========================================
  // FLOATING RATE INDEX MAPPING
  // ========================================

  // USD LIBOR
  if (indexName.includes('USD-LIBOR') || indexName.includes('USD_LIBOR')) {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_usd_libor',
      confidence: 90,
      reasoning: `Index "${indexName}" → CDM FloatingRateIndexEnum.USD_LIBOR. NOTE: USD LIBOR discontinued June 2023. Legacy trades only. New trades should use SOFR.`,
      indexCategory: 'libor',
      cdmIndexEnum: 'FloatingRateIndexEnum.USD_LIBOR',
      tenor: input.tenor
    }
  }

  // EUR EURIBOR
  if (indexName.includes('EUR-EURIBOR') || indexName.includes('EURIBOR')) {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_eur_euribor',
      confidence: 95,
      reasoning: `Index "${indexName}" → CDM FloatingRateIndexEnum.EUR_EURIBOR`,
      indexCategory: 'euribor',
      cdmIndexEnum: 'FloatingRateIndexEnum.EUR_EURIBOR',
      tenor: input.tenor
    }
  }

  // GBP LIBOR
  if (indexName.includes('GBP-LIBOR') || indexName.includes('GBP_LIBOR')) {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_gbp_libor',
      confidence: 95,
      reasoning: `Index "${indexName}" → CDM FloatingRateIndexEnum.GBP_LIBOR`,
      indexCategory: 'libor',
      cdmIndexEnum: 'FloatingRateIndexEnum.GBP_LIBOR',
      tenor: input.tenor
    }
  }

  // SOFR (USD risk-free rate)
  if (indexName.includes('SOFR') || indexName === 'USD-SOFR') {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_sofr',
      confidence: 95,
      reasoning: 'SOFR (Secured Overnight Financing Rate) → CDM FloatingRateIndexEnum.SOFR',
      indexCategory: 'sofr',
      cdmIndexEnum: 'FloatingRateIndexEnum.SOFR',
      tenor: input.tenor || 'ON'  // SOFR is overnight rate
    }
  }

  // SONIA (GBP risk-free rate)
  if (indexName.includes('SONIA') || indexName === 'GBP-SONIA') {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_sonia',
      confidence: 95,
      reasoning: 'SONIA (Sterling Overnight Index Average) → CDM FloatingRateIndexEnum.SONIA',
      indexCategory: 'sonia',
      cdmIndexEnum: 'FloatingRateIndexEnum.SONIA',
      tenor: input.tenor || 'ON'
    }
  }

  // ESTR (EUR risk-free rate)
  if (indexName.includes('ESTR') || indexName.includes('€STR')) {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_estr',
      confidence: 95,
      reasoning: 'ESTR (Euro Short-Term Rate) → CDM FloatingRateIndexEnum.ESTR',
      indexCategory: 'estr',
      cdmIndexEnum: 'FloatingRateIndexEnum.ESTR',
      tenor: input.tenor || 'ON'
    }
  }

  // TONAR (JPY risk-free rate)
  if (indexName.includes('TONAR') || indexName === 'JPY-TONAR') {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_tonar',
      confidence: 95,
      reasoning: 'TONAR (Tokyo Overnight Average Rate) → CDM FloatingRateIndexEnum.TONAR',
      indexCategory: 'tonar',
      cdmIndexEnum: 'FloatingRateIndexEnum.TONAR',
      tenor: input.tenor || 'ON'
    }
  }

  // Fed Funds
  if (indexName.includes('FED') && indexName.includes('FUND')) {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_fed_funds',
      confidence: 90,
      reasoning: 'Federal Funds Rate → CDM FloatingRateIndexEnum.FED_FUNDS',
      indexCategory: 'fed_funds',
      cdmIndexEnum: 'FloatingRateIndexEnum.FED_FUNDS',
      tenor: 'ON'
    }
  }

  // Prime Rate
  if (indexName.includes('PRIME')) {
    return {
      cdmPath: 'rateSpecification.floatingRate.rateOption',
      transformation: 'map_prime_rate',
      confidence: 85,
      reasoning: 'Prime Rate → CDM FloatingRateIndexEnum.PRIME',
      indexCategory: 'prime',
      cdmIndexEnum: 'FloatingRateIndexEnum.PRIME',
      tenor: input.tenor
    }
  }

  // ========================================
  // INDEX TENOR MAPPING
  // ========================================

  if (lowerName === 'indextenor' || lowerName === 'tenor') {
    // Parse tenor: "3M" → periodMultiplier=3, period=M
    const tenorMatch = input.fieldValue?.match(/^(\d+)([DMWY])$/i)

    if (tenorMatch) {
      const [_, multiplier, period] = tenorMatch
      return {
        cdmPath: 'rateSpecification.floatingRate.indexTenor',
        transformation: 'map_index_tenor',
        confidence: 95,
        reasoning: `Tenor "${input.fieldValue}" → CDM Period { periodMultiplier: ${multiplier}, period: ${period.toUpperCase()} }`,
        indexCategory: 'unknown',
        tenor: input.fieldValue,
        tenorPeriod: `${multiplier}${period.toUpperCase()}`
      }
    }

    return {
      cdmPath: 'rateSpecification.floatingRate.indexTenor',
      transformation: 'map_tenor',
      confidence: 80,
      reasoning: `Index tenor detected. Value: "${input.fieldValue}". Parse format: {number}{D|M|Y}`,
      indexCategory: 'unknown',
      tenor: input.fieldValue,
      todos: ['Parse tenor format and map to CDM Period structure']
    }
  }

  // ========================================
  // SPREAD & MULTIPLIER
  // ========================================

  if (lowerName === 'spread' || lowerName === 'spreadschedule') {
    return {
      cdmPath: 'rateSpecification.floatingRate.spread',
      transformation: 'map_spread',
      confidence: 95,
      reasoning: 'Spread field → CDM floatingRate.spread (added to floating rate)',
      indexCategory: 'unknown',
      unitType: 'rate'
    }
  }

  if (lowerName === 'multiplierschedule' || lowerName === 'multiplier') {
    return {
      cdmPath: 'rateSpecification.floatingRate.multiplier',
      transformation: 'map_multiplier',
      confidence: 90,
      reasoning: 'Multiplier field → CDM floatingRate.multiplier',
      indexCategory: 'unknown',
      unitType: 'multiplier'
    }
  }

  // ========================================
  // NO MATCH
  // ========================================

  return {
    cdmPath: `unmapped.floatingrate.${input.fieldName}`,
    transformation: 'not_floating_rate_field',
    confidence: 0,
    reasoning: `Field "${input.fieldName}" does not match floating rate index patterns.`,
    indexCategory: 'unknown'
  }
}
