// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import { z } from 'zod'
import { BaseSkillInput, BaseSkillOutput } from '../types'

/**
 * Input schema for floating-rate-index-resolver
 */
export const FloatingRateIndexResolverInput = BaseSkillInput.extend({
  indexName: z.string().optional(),         // USD-LIBOR-BBA, EUR-EURIBOR-Reuters
  tenor: z.string().optional()              // 1M, 3M, 6M, 12M
})

/**
 * Output schema for floating-rate-index-resolver
 */
export const FloatingRateIndexResolverOutput = BaseSkillOutput.extend({
  indexCategory: z.enum([
    'libor',
    'euribor',
    'sofr',
    'sonia',
    'estr',
    'tonar',
    'prime',
    'fed_funds',
    'unknown'
  ]),
  cdmIndexEnum: z.string().optional(),      // FloatingRateIndexEnum value
  tenor: z.string().optional(),             // Normalized tenor (3M)
  tenorPeriod: z.string().optional()        // CDM Period (3, M)
})

export type FloatingRateIndexResolverInput = z.infer<typeof FloatingRateIndexResolverInput>
export type FloatingRateIndexResolverOutput = z.infer<typeof FloatingRateIndexResolverOutput>
