// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { Skill } from '../types'
import { IRSwapResolverInput, IRSwapResolverOutput } from './schemas'
import { irSwapResolverLogic } from './logic'
import { registerSkill } from '../registry'

export const irSwapResolverSkill: Skill = {
  name: 'ir_swap_resolver',
  description: 'Maps interest rate derivative products (swaps, swaptions, caps/floors, FRAs) from FPML to CDM InterestRatePayout structures. Handles vanilla swaps, basis swaps, cross-currency swaps, and IR options.',
  inputSchema: IRSwapResolverInput,
  outputSchema: IRSwapResolverOutput,
  fn: irSwapResolverLogic,
  triggers: {
    keywords: [
      'swap',
      'swaption',
      'capfloor',
      'cap',
      'floor',
      'fra',
      'swapstream',
      'fixedrate',
      'floatingrate'
    ],
    patterns: [
      /.*[Ss]wap.*/,
      /.*[Ss]waption.*/,
      /.*[Rr]ate.*/
    ]
  }
}

// Auto-register on import
registerSkill(irSwapResolverSkill)
