// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17
//
// INSTRUCTIONS FOR USER REVIEW:
// 1. Verify swap type detection matches your institution's FPML structure
// 2. Add any exotic swap types specific to your products
// 3. Confirm fixed vs floating rate detection logic

import type { IRSwapResolverInput, IRSwapResolverOutput } from './schemas'

/**
 * Interest Rate Swap Resolver Logic
 *
 * SCHEMA ANALYSIS:
 * - FPML IR products: swap, swaption, capFloor, fra
 * - CDM maps to: InterestRatePayout (for swaps), OptionPayout (for swaptions)
 * - Swap streams: each stream → separate InterestRatePayout
 * - Rate types: fixed, floating (floatingRateCalculation), inflation
 *
 * PRODUCT PATTERNS:
 * - Vanilla swap: 2 streams (fixed + floating)
 * - Basis swap: 2 floating streams
 * - Cross-currency swap: 2 streams with different currencies
 * - Swaption: option on swap
 * - Cap/Floor: interest rate option with cap/floor rates
 * - FRA: forward rate agreement
 *
 * CONFIDENCE RULES:
 * - 95%: Direct product type match (swap, swaption)
 * - 90%: Stream-level mapping (swapStream → InterestRatePayout)
 * - 80%: Rate type detection (fixedRateSchedule vs floatingRateCalculation)
 */
export const irSwapResolverLogic = (input: IRSwapResolverInput): IRSwapResolverOutput => {
  const lowerName = input.fieldName.toLowerCase()
  const path = input.fieldPath.toLowerCase()
  const contextStr = JSON.stringify(input.context || {}).toLowerCase()

  // ========================================
  // SWAP DETECTION
  // ========================================

  // Vanilla swap
  if (lowerName === 'swap' || path.includes('/swap/')) {
    return {
      cdmPath: 'tradableProduct.product.contractualProduct.economicTerms.payout',
      transformation: 'map_vanilla_swap',
      confidence: 95,
      reasoning: 'Swap detected → CDM InterestRatePayout[] (one payout per stream)',
      productCategory: 'vanilla_swap',
      payoutType: 'InterestRatePayout',
      todos: [
        'Map each swapStream to separate InterestRatePayout',
        'Determine if this is vanilla, basis, or cross-currency swap from stream analysis'
      ]
    }
  }

  // Swap stream (component of swap)
  if (lowerName === 'swapstream' || path.includes('swapstream')) {
    // Detect rate type from context
    let rateType: 'fixed' | 'floating' | 'unknown' = 'unknown'

    if (contextStr.includes('fixedrate') || contextStr.includes('fixedamount')) {
      rateType = 'fixed'
    } else if (contextStr.includes('floatingrate') || contextStr.includes('floatingratecalculation')) {
      rateType = 'floating'
    }

    return {
      cdmPath: 'payout[i]',  // Array index determined by stream order
      transformation: 'map_swap_stream',
      confidence: 95,
      reasoning: `Swap stream → CDM InterestRatePayout. Rate type: ${rateType}`,
      productCategory: 'vanilla_swap',
      payoutType: 'InterestRatePayout',
      rateType,
      todos: [
        'Determine array index based on stream order',
        'Map payerPartyReference → payerReceiver.payer',
        'Map receiverPartyReference → payerReceiver.receiver'
      ]
    }
  }

  // ========================================
  // RATE TYPE DETECTION
  // ========================================

  // Fixed rate schedule
  if (lowerName.includes('fixedrate') || lowerName === 'fixedrateschedule') {
    return {
      cdmPath: 'payout.rateSpecification.fixedRate',
      transformation: 'map_fixed_rate',
      confidence: 95,
      reasoning: 'Fixed rate schedule → CDM rateSpecification.fixedRate',
      productCategory: 'vanilla_swap',
      payoutType: 'InterestRatePayout',
      rateType: 'fixed'
    }
  }

  // Floating rate calculation
  if (lowerName.includes('floatingrate') || lowerName === 'floatingratecalculation') {
    return {
      cdmPath: 'payout.rateSpecification.floatingRate',
      transformation: 'map_floating_rate',
      confidence: 95,
      reasoning: 'Floating rate calculation → CDM rateSpecification.floatingRate',
      productCategory: 'vanilla_swap',
      payoutType: 'InterestRatePayout',
      rateType: 'floating'
    }
  }

  // ========================================
  // SWAPTION
  // ========================================

  if (lowerName === 'swaption' || path.includes('/swaption/')) {
    return {
      cdmPath: 'tradableProduct.product.contractualProduct.economicTerms.payout',
      transformation: 'map_swaption',
      confidence: 90,
      reasoning: 'Swaption detected → CDM OptionPayout (option on underlying swap)',
      productCategory: 'swaption',
      payoutType: 'OptionPayout',
      todos: [
        'Map underlying swap to OptionPayout.underlier',
        'Map exercise terms (European, American, Bermuda)',
        'Map premium payment terms'
      ]
    }
  }

  // ========================================
  // CAP/FLOOR
  // ========================================

  if (lowerName === 'capfloor' || lowerName === 'cap' || lowerName === 'floor') {
    return {
      cdmPath: 'tradableProduct.product.contractualProduct.economicTerms.payout',
      transformation: 'map_cap_floor',
      confidence: 90,
      reasoning: 'Cap/Floor detected → CDM InterestRatePayout with capRate/floorRate',
      productCategory: 'cap_floor',
      payoutType: 'InterestRatePayout',
      todos: [
        'Map capRate → priceSchedule with operator=Max',
        'Map floorRate → priceSchedule with operator=Min',
        'Handle cap-only, floor-only, or collar structures'
      ]
    }
  }

  // ========================================
  // FRA (Forward Rate Agreement)
  // ========================================

  if (lowerName === 'fra' || lowerName === 'forwardrateagreement') {
    return {
      cdmPath: 'tradableProduct.product.contractualProduct.economicTerms.payout',
      transformation: 'map_fra',
      confidence: 90,
      reasoning: 'FRA detected → CDM InterestRatePayout (single period)',
      productCategory: 'fra',
      payoutType: 'InterestRatePayout',
      todos: [
        'Map FRA-specific fields: fraDiscounting, fixingDateOffset',
        'Ensure single calculation period (FRA characteristic)'
      ]
    }
  }

  // ========================================
  // CALCULATION PERIOD AMOUNT
  // ========================================

  if (lowerName === 'calculationperiodamount' || path.includes('calculationperiodamount')) {
    return {
      cdmPath: 'payout.priceQuantity',
      transformation: 'map_calculation_period_amount',
      confidence: 90,
      reasoning: 'Calculation period amount → CDM priceQuantity (contains notional, rate, day count)',
      productCategory: 'vanilla_swap',
      payoutType: 'InterestRatePayout',
      todos: [
        'Map nested elements: notional, fixedRate/floatingRate, dayCountFraction',
        'Handle notional step schedules (changing notional over time)'
      ]
    }
  }

  // ========================================
  // NO MATCH
  // ========================================

  return {
    cdmPath: `unmapped.ir.${input.fieldName}`,
    transformation: 'not_ir_swap_field',
    confidence: 0,
    reasoning: `Field "${input.fieldName}" does not match IR swap patterns. May belong to different product type.`,
    productCategory: 'unknown',
    payoutType: 'InterestRatePayout'
  }
}
