// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import { z } from 'zod'
import { BaseSkillInput, BaseSkillOutput } from '../types'

/**
 * Input schema for ir-swap-resolver
 */
export const IRSwapResolverInput = BaseSkillInput.extend({
  productType: z.string().optional(),       // swap, swaption, capFloor, fra
  streamType: z.string().optional()         // fixed, floating
})

/**
 * Output schema for ir-swap-resolver
 */
export const IRSwapResolverOutput = BaseSkillOutput.extend({
  productCategory: z.enum([
    'vanilla_swap',
    'basis_swap',
    'cross_currency_swap',
    'swaption',
    'cap_floor',
    'fra',
    'unknown'
  ]),
  payoutType: z.enum(['InterestRatePayout', 'OptionPayout']),
  rateType: z.enum(['fixed', 'floating', 'unknown']).optional()
})

export type IRSwapResolverInput = z.infer<typeof IRSwapResolverInput>
export type IRSwapResolverOutput = z.infer<typeof IRSwapResolverOutput>
