// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17
//
// Central skill registration
// Each import triggers registerSkill() via side effect
// To add a new skill: create the module, add one line below

// Week 1: Must-have skills (party, temporal, cardinality, units)
import './party-resolver'
import './temporal-mapper'
import './cardinality-checker'
import './unit-normalizer'

// Week 2: Should-have skills (IR swaps, floating rate indexes)
import './ir-swap-resolver'
import './floating-rate-index-resolver'

// Week 3+: Nice-to-have skills (product-specific)
// Uncomment as you add more skills:
// import './fx-derivatives-resolver'
// import './equity-derivatives-resolver'
// import './credit-derivatives-resolver'
// import './exercise-terms-resolver'
// import './settlement-terms-resolver'
// import './commodity-derivatives-resolver'

console.log('[Skills] All skills registered')
