// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { Skill } from './types'

const registry = new Map<string, Skill>()

/**
 * Register a skill in the global registry
 */
export const registerSkill = (skill: Skill): void => {
  console.log(`[Registry] Registered skill: ${skill.name}`)
  registry.set(skill.name, skill)
}

/**
 * Get a skill by name
 */
export const getSkill = (name: string): Skill | undefined => {
  return registry.get(name)
}

/**
 * Get all registered skills
 */
export const getAllSkills = (): Skill[] => {
  return Array.from(registry.values())
}

/**
 * Match skills to a field based on trigger conditions.
 * A skill triggers if ANY of its trigger conditions match:
 * - Field name contains any keyword (case-insensitive)
 * - Field type matches any fieldType
 * - Field name matches any regex pattern
 */
export const matchSkills = (field: {
  name: string
  type?: string
  path?: string
}): Skill[] => {
  const matched: Skill[] = []

  for (const skill of registry.values()) {
    if (shouldTrigger({ name: field.name, type: field.type, path: field.path }, skill.triggers)) {
      matched.push(skill)
    }
  }

  return matched
}

/**
 * Determine if a skill should trigger for a given field
 */
const shouldTrigger = (
  field: { name: string; type?: string; path?: string },
  triggers: Skill['triggers']
): boolean => {
  // Check keywords (case-insensitive)
  if (triggers.keywords) {
    const lowerName = field.name.toLowerCase()
    if (triggers.keywords.some(kw => lowerName.includes(kw.toLowerCase()))) {
      return true
    }
  }

  // Check field types
  if (triggers.fieldTypes && field.type) {
    if (triggers.fieldTypes.includes(field.type)) {
      return true
    }
  }

  // Check regex patterns
  if (triggers.patterns) {
    if (triggers.patterns.some(pattern => pattern.test(field.name))) {
      return true
    }
  }

  if (triggers.pathKeywords && field.path) {
    const p = field.path.toLowerCase()
    if (triggers.pathKeywords.some(kw => p.includes(kw.toLowerCase()))) {
      return true
    }
  }

  return false
}
