// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import { z } from 'zod'

/**
 * Skill interface - all skills implement this
 */
export interface Skill {
  name: string
  description: string
  inputSchema: z.ZodSchema
  outputSchema: z.ZodSchema
  fn: (input: any) => any | Promise<any>
  triggers: {
    keywords?: string[]      // Field name contains any of these → trigger
    fieldTypes?: string[]     // Field type matches any of these → trigger
    patterns?: RegExp[]       // Field name matches regex → trigger
  }
}

/**
 * Base input schema for all skills
 */
export const BaseSkillInput = z.object({
  fieldName: z.string(),
  fieldValue: z.string().optional(),
  fieldPath: z.string(),
  fieldType: z.string().optional(),
  context: z.record(z.any()).optional()  // Extra metadata from parser
})

/**
 * Base output schema for all skills
 */
export const BaseSkillOutput = z.object({
  cdmPath: z.string(),                    // Target CDM path (e.g., "party.buyer")
  transformation: z.string(),              // Transformation note (e.g., "map_party_role")
  confidence: z.number().min(0).max(100),  // Confidence score 0-100
  reasoning: z.string(),                   // Human-readable explanation
  todos: z.array(z.string()).optional()    // TODO items for user review
})

export type BaseSkillInput = z.infer<typeof BaseSkillInput>
export type BaseSkillOutput = z.infer<typeof BaseSkillOutput>
