// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { Skill } from '../types'
import { PartyResolverInput, PartyResolverOutput } from './schemas'
import { partyResolverLogic } from './logic'
import { registerSkill } from '../registry'

export const partyResolverSkill: Skill = {
  name: 'party_resolver',
  description: 'Maps party role fields (buyer, seller, payer, payee, counterparty) from FPML to CDM party structures. Handles both semantic roles and directional payment references.',
  inputSchema: PartyResolverInput,
  outputSchema: PartyResolverOutput,
  fn: input => {
    const output = partyResolverLogic(input)
    return {
      ...output,
      meaning: output.meaning ?? 'party-role-mapping',
      economicCategory: output.economicCategory ?? 'counterparty',
      ambiguityFlags:
        output.confidence < 70
          ? [...(output.ambiguityFlags ?? []), 'low_confidence_party_resolution']
          : output.ambiguityFlags,
      inferenceBasis: output.inferenceBasis ?? 'party_resolver_rule_set',
      patternSource: output.patternSource ?? 'fpml_party_patterns',
      confidenceRationale:
        output.confidenceRationale ??
        `Derived from party role heuristics with confidence ${output.confidence}.`,
    }
  },
  triggers: {
    keywords: [
      'buyer',
      'seller',
      'counterparty',
      'payer',
      'payee',
      'receiver',
      'party'
    ],
    patterns: [
      /.*[Pp]arty.*/,
      /.*[Bb]uyer.*/,
      /.*[Ss]eller.*/,
      /.*[Pp]ayer.*/,
      /.*[Pp]ayee.*/
    ]
  }
}

// Auto-register on import
registerSkill(partyResolverSkill)
