// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import { z } from 'zod'
import { BaseSkillInput, BaseSkillOutput } from '../types'

/**
 * Input schema for party-resolver
 */
export const PartyResolverInput = BaseSkillInput.extend({
  // No additional fields needed - uses base schema
})

/**
 * Output schema for party-resolver
 */
export const PartyResolverOutput = BaseSkillOutput.extend({
  partyRole: z.enum([
    'buyer',
    'seller',
    'counterparty',
    'payer',
    'payee',
    'receiver',
    'party_1',
    'party_2',
    'calculation_agent',
    'unknown'
  ]),
  cdmCounterpartyRole: z.enum(['PARTY_1', 'PARTY_2', 'NONE']).optional()
})

export type PartyResolverInput = z.infer<typeof PartyResolverInput>
export type PartyResolverOutput = z.infer<typeof PartyResolverOutput>
