-- Uploaded formats (original XML/JSON)
CREATE TABLE IF NOT EXISTS uploads (
  id TEXT PRIMARY KEY,
  filename TEXT NOT NULL,
  content TEXT NOT NULL,
  format_type TEXT NOT NULL,
  uploaded_at TEXT NOT NULL,
  uploaded_by TEXT NOT NULL
);

-- Parsed fields (intermediate representation)
CREATE TABLE IF NOT EXISTS fields (
  id TEXT PRIMARY KEY,
  upload_id TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT,
  path TEXT NOT NULL,
  value TEXT,
  context TEXT,
  is_array INTEGER,
  min_occurs INTEGER,
  max_occurs TEXT,
  FOREIGN KEY (upload_id) REFERENCES uploads(id)
);

-- Mapping proposals (generated by agent)
CREATE TABLE IF NOT EXISTS proposals (
  id TEXT PRIMARY KEY,
  upload_id TEXT NOT NULL,
  field_id TEXT NOT NULL,
  cdm_path TEXT NOT NULL,
  transformation TEXT NOT NULL,
  confidence INTEGER NOT NULL,
  reasoning TEXT NOT NULL,
  skill_invoked TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  needs_review INTEGER NOT NULL DEFAULT 0,
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  FOREIGN KEY (upload_id) REFERENCES uploads(id),
  FOREIGN KEY (field_id) REFERENCES fields(id)
);

-- Approved mappings (analyst reviewed)
CREATE TABLE IF NOT EXISTS approved_mappings (
  id TEXT PRIMARY KEY,
  proposal_id TEXT NOT NULL,
  cdm_path TEXT NOT NULL,
  transformation TEXT NOT NULL,
  approved_by TEXT NOT NULL,
  approved_at TEXT NOT NULL,
  notes TEXT,
  FOREIGN KEY (proposal_id) REFERENCES proposals(id)
);

-- Failed mappings (for refinement)
CREATE TABLE IF NOT EXISTS failed_mappings (
  id TEXT PRIMARY KEY,
  field_id TEXT NOT NULL,
  proposal_id TEXT NOT NULL,
  analyst_correction TEXT NOT NULL,
  analyst_notes TEXT,
  failed_at TEXT NOT NULL,
  FOREIGN KEY (field_id) REFERENCES fields(id),
  FOREIGN KEY (proposal_id) REFERENCES proposals(id)
);

-- Exports
CREATE TABLE IF NOT EXISTS exports (
  id TEXT PRIMARY KEY,
  upload_id TEXT NOT NULL,
  rosetta_json TEXT NOT NULL,
  exported_by TEXT NOT NULL,
  exported_at TEXT NOT NULL,
  FOREIGN KEY (upload_id) REFERENCES uploads(id)
);

-- Audit trail
CREATE TABLE IF NOT EXISTS audit_log (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,
  user TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  metadata TEXT
);
