// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { Skill } from '../types'
import { CardinalityCheckerInput, CardinalityCheckerOutput } from './schemas'
import { cardinalityCheckerLogic } from './logic'
import { registerSkill } from '../registry'

export const cardinalityCheckerSkill: Skill = {
  name: 'cardinality_checker',
  description: 'Determines cardinality (0..1, 1..1, 0..*, 1..*, N..N) for FPML fields and maps to CDM cardinality. Analyzes schema metadata, field name patterns, and parser-detected structure.',
  inputSchema: CardinalityCheckerInput,
  outputSchema: CardinalityCheckerOutput,
  fn: cardinalityCheckerLogic,
  triggers: {
    // Cardinality checker runs on ALL fields (no specific triggers)
    // It provides cardinality metadata for other skills to use
    keywords: [],
    fieldTypes: [],
    patterns: []
  }
}

// Auto-register on import
registerSkill(cardinalityCheckerSkill)
