// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { CardinalityCheckerInput, CardinalityCheckerOutput } from './schemas'

/**
 * Cardinality Checker Logic
 *
 * SCHEMA ANALYSIS:
 * - FPML uses XSD minOccurs/maxOccurs: 0, 1, unbounded
 * - CDM uses Rosetta cardinality: 0..1, 1..1, 0..*, 1..*, N..N (fixed)
 * - Array detection: plural field names, maxOccurs > 1, parser-detected arrays
 *
 * CARDINALITY PATTERNS:
 * 1. minOccurs=0, maxOccurs=1 → 0..1 (optional single)
 * 2. minOccurs=1, maxOccurs=1 → 1..1 (required single)
 * 3. minOccurs=0, maxOccurs=unbounded → 0..* (optional array)
 * 4. minOccurs=1, maxOccurs=unbounded → 1..* (required array)
 * 5. minOccurs=N, maxOccurs=N → N..N (fixed count, e.g., 2..2 for counterparties)
 *
 * CONFIDENCE RULES:
 * - 95%: Explicit schema cardinality + field name agrees (trades + maxOccurs=unbounded)
 * - 85%: Field name pattern suggests cardinality (plural → array)
 * - 70%: Inferred from context without schema info
 */
export const cardinalityCheckerLogic = (
  input: CardinalityCheckerInput
): CardinalityCheckerOutput => {
  const lowerName = input.fieldName.toLowerCase()

  // ========================================
  // EXPLICIT CARDINALITY (from schema)
  // ========================================

  if (input.minOccurs !== undefined && input.maxOccurs !== undefined) {
    const min = input.minOccurs
    const max = input.maxOccurs === 'unbounded' ? Infinity : input.maxOccurs

    // Optional single (0..1)
    if (min === 0 && max === 1) {
      return {
        cdmPath: input.fieldPath,
        transformation: 'optional_single',
        confidence: 95,
        reasoning: `Schema cardinality: minOccurs=${min}, maxOccurs=${max} → CDM 0..1 (optional single value)`,
        fpmlCardinality: '0..1',
        cdmCardinality: '0..1',
        isOptional: true,
        isArray: false,
        requiresArrayNotation: false
      }
    }

    // Required single (1..1)
    if (min === 1 && max === 1) {
      return {
        cdmPath: input.fieldPath,
        transformation: 'required_single',
        confidence: 95,
        reasoning: `Schema cardinality: minOccurs=${min}, maxOccurs=${max} → CDM 1..1 (required single value)`,
        fpmlCardinality: '1..1',
        cdmCardinality: '1..1',
        isOptional: false,
        isArray: false,
        requiresArrayNotation: false
      }
    }

    // Optional array (0..*)
    if (min === 0 && max === Infinity) {
      return {
        cdmPath: `${input.fieldPath}[]`,
        transformation: 'optional_array',
        confidence: 95,
        reasoning: `Schema cardinality: minOccurs=${min}, maxOccurs=unbounded → CDM 0..* (optional array)`,
        fpmlCardinality: '0..*',
        cdmCardinality: '0..*',
        isOptional: true,
        isArray: true,
        requiresArrayNotation: true
      }
    }

    // Required array (1..*)
    if (min === 1 && max === Infinity) {
      return {
        cdmPath: `${input.fieldPath}[]`,
        transformation: 'required_array',
        confidence: 95,
        reasoning: `Schema cardinality: minOccurs=${min}, maxOccurs=unbounded → CDM 1..* (required array, at least one element)`,
        fpmlCardinality: '1..*',
        cdmCardinality: '1..*',
        isOptional: false,
        isArray: true,
        requiresArrayNotation: true
      }
    }

    // Fixed count (N..N)
    if (min === max && max !== Infinity) {
      return {
        cdmPath: `${input.fieldPath}[]`,
        transformation: 'fixed_array',
        confidence: 95,
        reasoning: `Schema cardinality: minOccurs=${min}, maxOccurs=${max} → CDM ${min}..${max} (fixed array length)`,
        fpmlCardinality: `${min}..${max}`,
        cdmCardinality: `${min}..${max}`,
        isOptional: min === 0,
        isArray: true,
        requiresArrayNotation: true
      }
    }

    // Bounded array (M..N where M < N)
    if (max !== Infinity && min < max) {
      return {
        cdmPath: `${input.fieldPath}[]`,
        transformation: 'bounded_array',
        confidence: 90,
        reasoning: `Schema cardinality: minOccurs=${min}, maxOccurs=${max} → CDM ${min}..${max} (bounded array)`,
        fpmlCardinality: `${min}..${max}`,
        cdmCardinality: `${min}..${max}`,
        isOptional: min === 0,
        isArray: true,
        requiresArrayNotation: true
      }
    }
  }

  // ========================================
  // INFERRED CARDINALITY (from field name)
  // ========================================

  // Plural field name → array
  if (lowerName.endsWith('s') && !lowerName.endsWith('ss')) {
    // Common plural patterns: trades, payments, parties, dates
    // But exclude: class, process, business (end in 's' but not plural)

    const singularExceptions = [
      'class',
      'process',
      'business',
      'status',
      'basis',
      'gross',
      'address'
    ]

    if (!singularExceptions.some(ex => lowerName === ex || lowerName.endsWith(ex))) {
      return {
        cdmPath: `${input.fieldPath}[]`,
        transformation: 'plural_implies_array',
        confidence: 85,
        reasoning: `Field name "${input.fieldName}" is plural (ends in 's') → inferred as array. CDM cardinality likely 0..* or 1..*`,
        fpmlCardinality: '0..*',
        cdmCardinality: '0..*',
        isOptional: true,  // Conservative: assume optional unless schema says otherwise
        isArray: true,
        requiresArrayNotation: true,
        todos: ['Verify: Should this be 0..* or 1..* (optional vs required array)?']
      }
    }
  }

  // Parser detected array structure
  if (input.isArray === true) {
    return {
      cdmPath: `${input.fieldPath}[]`,
      transformation: 'parser_detected_array',
      confidence: 90,
      reasoning: 'Parser detected array structure in source data → CDM array type',
      fpmlCardinality: '0..*',
      cdmCardinality: '0..*',
      isOptional: true,
      isArray: true,
      requiresArrayNotation: true,
      todos: ['Check schema for exact cardinality bounds']
    }
  }

  // ========================================
  // DEFAULT: REQUIRED SINGLE
  // ========================================

  // Conservative default: if no cardinality info, assume required single
  return {
    cdmPath: input.fieldPath,
    transformation: 'default_single',
    confidence: 70,
    reasoning: `No cardinality information available for "${input.fieldName}". Defaulting to 1..1 (required single). Verify with schema.`,
    fpmlCardinality: '1..1',
    cdmCardinality: '1..1',
    isOptional: false,
    isArray: false,
    requiresArrayNotation: false,
    todos: ['Check FPML schema to confirm actual cardinality']
  }
}
