// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import { z } from 'zod'
import { BaseSkillInput, BaseSkillOutput } from '../types'

/**
 * Input schema for cardinality-checker
 */
export const CardinalityCheckerInput = BaseSkillInput.extend({
  isArray: z.boolean().optional(),           // Parser detected array structure
  minOccurs: z.number().optional(),          // From XSD schema
  maxOccurs: z.union([z.number(), z.literal('unbounded')]).optional()
})

/**
 * Output schema for cardinality-checker
 */
export const CardinalityCheckerOutput = BaseSkillOutput.extend({
  fpmlCardinality: z.string(),               // Original FPML cardinality (0..1, 1..*, etc.)
  cdmCardinality: z.string(),                // Target CDM cardinality
  isOptional: z.boolean(),                   // 0..x means optional
  isArray: z.boolean(),                      // x..* or x..N means array
  requiresArrayNotation: z.boolean()         // Should CDM path include []
})

export type CardinalityCheckerInput = z.infer<typeof CardinalityCheckerInput>
export type CardinalityCheckerOutput = z.infer<typeof CardinalityCheckerOutput>
