// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import type { Skill } from '../types'
import { UnitNormalizerInput, UnitNormalizerOutput } from './schemas'
import { unitNormalizerLogic } from './logic'
import { registerSkill } from '../registry'

export const unitNormalizerSkill: Skill = {
  name: 'unit_normalizer',
  description: 'Maps currency codes, quantity units, amounts, prices, and rates from FPML to CDM unit structures. Handles ISO 4217 currencies, commodity units (BBL, MT, MWh), and financial multipliers.',
  inputSchema: UnitNormalizerInput,
  outputSchema: UnitNormalizerOutput,
  fn: unitNormalizerLogic,
  triggers: {
    keywords: [
      'currency',
      'amount',
      'notional',
      'quantity',
      'unit',
      'price',
      'rate',
      'percent',
      'multiplier'
    ],
    patterns: [
      /.*[Cc]urrency.*/,
      /.*[Aa]mount.*/,
      /.*[Qq]uantity.*/,
      /.*[Pp]rice.*/,
      /.*[Rr]ate.*/
    ]
  }
}

// Auto-register on import
registerSkill(unitNormalizerSkill)
