// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17
//
// INSTRUCTIONS FOR USER REVIEW:
// 1. Verify currency codes match your institution's usage
// 2. Add any missing commodity units (BBL, MT, MWh, etc.)
// 3. Confirm enum mappings align with CDM version you're using

import type { UnitNormalizerInput, UnitNormalizerOutput } from './schemas'

/**
 * Unit Normalizer Logic
 *
 * SCHEMA ANALYSIS:
 * - FPML uses: currency codes (USD, EUR), quantity units (BBL, MT), amounts
 * - CDM uses: CurrencyCodeEnum, UnitEnum, Quantity types
 * - Need to map: currency → CurrencyCodeEnum, quantityUnit → UnitEnum
 *
 * UNIT CATEGORIES:
 * 1. Currency: USD, EUR, GBP, JPY, CHF, etc. (ISO 4217)
 * 2. Commodity: BBL (barrels), MT (metric tons), MWh (megawatt-hours)
 * 3. Financial: notional amounts, quantity, multiplier, percentage
 *
 * CONFIDENCE RULES:
 * - 95%: ISO currency code → CurrencyCodeEnum
 * - 90%: Standard commodity unit → UnitEnum
 * - 85%: Amount/notional field recognition
 * - 70%: Generic quantity field
 */
export const unitNormalizerLogic = (input: UnitNormalizerInput): UnitNormalizerOutput => {
  const lowerName = input.fieldName.toLowerCase()
  const value = input.fieldValue?.toUpperCase() || ''

  if (lowerName === 'tradeid' || lowerName.endsWith('tradeid')) {
    const idx = input.fieldPath.match(/\[(\d+)\]/g)?.pop()?.match(/(\d+)/)?.[1]
    const suffix = idx != null ? `_${idx}` : ''
    return {
      cdmPath: `packageMeta.fpmlTradeId${suffix}`,
      transformation: 'map_fpml_trade_identifier',
      confidence: 55,
      reasoning:
        'Trade-level identifier from FPML (e.g. party-scoped tradeId) — not always the CDM trade identifier shape; mirrored to packageMeta until roster rules land.',
      unitType: 'unknown',
    }
  }

  if (lowerName === 'quotebasis' || (lowerName.includes('quote') && lowerName.endsWith('basis'))) {
    return {
      cdmPath: 'packageMeta.fpmlFxQuotedCurrencyPair.quoteBasis',
      transformation: 'map_fpml_quote_basis',
      confidence: 72,
      reasoning:
        'FX quote basis (Currency2PerCurrency1, etc.) maps to quoted-currency-pair semantics; packageMeta until FX payout IR is wired to priceQuantity.',
      unitType: 'unknown',
    }
  }

  // ========================================
  // CURRENCY (ISO 4217 codes)
  // ========================================

  // ISO 4217 currency codes (45 major trading currencies)
  const currencyCodes = [
    // G10 currencies
    'USD', 'EUR', 'GBP', 'JPY', 'CHF', 'AUD', 'CAD', 'NZD', 'SEK', 'NOK', 'DKK',

    // Major Asian
    'CNY', 'HKD', 'SGD', 'KRW', 'INR', 'THB', 'MYR', 'IDR', 'PHP', 'TWD',

    // Latin America
    'BRL', 'MXN', 'ARS', 'CLP', 'COP', 'PEN',

    // EMEA
    'ZAR', 'RUB', 'TRY', 'PLN', 'CZK', 'HUF', 'ILS', 'SAR', 'AED', 'EGP',

    // Other major
    'ISK', 'RON', 'BGN', 'HRK'
  ]

  if (lowerName === 'currency' || lowerName === 'settlementcurrency' ||
      lowerName === 'notionalcurrency' || lowerName === 'paymentcurrency') {
    return {
      cdmPath: 'currency',
      transformation: 'map_currency_enum',
      confidence: 95,
      reasoning: `Currency field → CDM CurrencyCodeEnum. Field: "${input.fieldName}"`,
      unitType: 'currency',
      normalizedUnit: value || undefined,
      cdmEnum: value ? `CurrencyCodeEnum.${value}` : undefined
    }
  }

  // Currency in field value
  if (currencyCodes.includes(value)) {
    return {
      cdmPath: 'currency',
      transformation: 'infer_currency_from_value',
      confidence: 90,
      reasoning: `Value "${value}" is ISO 4217 currency code → CDM CurrencyCodeEnum`,
      unitType: 'currency',
      normalizedUnit: value,
      cdmEnum: `CurrencyCodeEnum.${value}`
    }
  }

  // ========================================
  // AMOUNTS & NOTIONAL
  // ========================================

  // Notional amount
  if (lowerName.includes('notional') && lowerName.includes('amount')) {
    return {
      cdmPath: 'priceQuantity.quantity.amount',
      transformation: 'map_notional_amount',
      confidence: 95,
      reasoning: 'Keyword match: notionalAmount → CDM priceQuantity.quantity.amount (notional principal)',
      unitType: 'notional'
    }
  }

  // Generic amount
  if (lowerName === 'amount' || lowerName.endsWith('amount')) {
    return {
      cdmPath: 'quantity.amount',
      transformation: 'map_amount',
      confidence: 85,
      reasoning: `Amount field → CDM quantity.amount. Context: "${input.fieldName}"`,
      unitType: 'amount',
      todos: ['Verify: Is this notional, payment, or settlement amount?']
    }
  }

  // ========================================
  // QUANTITY & UNITS
  // ========================================

  // Commodity units (16 standard units)
  const commodityUnits: Record<string, string> = {
    // Energy
    'BBL': 'Barrels (crude oil)',
    'MMBBL': 'Million barrels',
    'GAL': 'Gallons',
    'MWH': 'Megawatt-hours (power)',
    'MMBTU': 'Million BTU (natural gas)',
    'THERM': 'Therms (natural gas)',

    // Metals
    'MT': 'Metric tons',
    'KG': 'Kilograms',
    'LBS': 'Pounds',
    'TOZ': 'Troy ounces (precious metals)',
    'G': 'Grams',

    // Agriculture
    'BU': 'Bushels (grains)',
    'CWT': 'Hundredweight',

    // Other
    'LOTS': 'Standard lots',
    'CONTRACTS': 'Futures contracts'
  }

  if (lowerName.includes('quantity') || lowerName === 'quantity') {
    const unit = input.unit?.toUpperCase() || value

    if (unit && commodityUnits[unit]) {
      return {
        cdmPath: 'priceQuantity.quantity',
        transformation: 'map_commodity_quantity',
        confidence: 90,
        reasoning: `Quantity with unit "${unit}" (${commodityUnits[unit]}) → CDM quantity with UnitEnum`,
        unitType: 'quantity',
        normalizedUnit: unit,
        cdmEnum: `UnitEnum.${unit}`
      }
    }

    return {
      cdmPath: 'priceQuantity.quantity',
      transformation: 'map_quantity',
      confidence: 85,
      reasoning: 'Quantity field → CDM priceQuantity.quantity',
      unitType: 'quantity',
      todos: ['Determine quantity unit if not specified']
    }
  }

  // Quantity unit field
  if (lowerName === 'quantityunit' || lowerName === 'unit') {
    const unit = value || input.unit?.toUpperCase()

    if (unit && commodityUnits[unit]) {
      return {
        cdmPath: 'quantity.unit',
        transformation: 'map_unit_enum',
        confidence: 90,
        reasoning: `Unit "${unit}" → CDM UnitEnum.${unit}`,
        unitType: 'quantity',
        normalizedUnit: unit,
        cdmEnum: `UnitEnum.${unit}`
      }
    }

    return {
      cdmPath: 'quantity.unit',
      transformation: 'map_unknown_unit',
      confidence: 70,
      reasoning: 'Unit field detected but value not recognized. May need custom unit mapping.',
      unitType: 'quantity',
      normalizedUnit: unit,
      todos: ['Add mapping for unit: ' + (unit || 'unknown')]
    }
  }

  // ========================================
  // PRICE & RATE
  // ========================================

  // Price
  if (lowerName.includes('price') && !lowerName.includes('strike')) {
    return {
      cdmPath: 'priceQuantity.price',
      transformation: 'map_price',
      confidence: 85,
      reasoning: `Price field → CDM priceQuantity.price. Context: "${input.fieldName}"`,
      unitType: 'price',
      todos: ['Determine if this is spot price, strike price, or price schedule']
    }
  }

  // Rate (interest rate, FX rate, etc.)
  if (lowerName.includes('rate') && !lowerName.includes('cardinality')) {
    return {
      cdmPath: 'rateSchedule',
      transformation: 'map_rate',
      confidence: 80,
      reasoning: `Rate field → CDM rate structure. Context: "${input.fieldName}"`,
      unitType: 'rate',
      todos: ['Determine if this is fixed rate, floating rate, spread, or FX rate']
    }
  }

  // ========================================
  // PERCENTAGE & MULTIPLIER
  // ========================================

  // Percentage
  if (lowerName.includes('percent') || lowerName.includes('pct')) {
    return {
      cdmPath: 'percentage',
      transformation: 'map_percentage',
      confidence: 85,
      reasoning: 'Percentage field detected → CDM numeric with percentage interpretation',
      unitType: 'percentage'
    }
  }

  // Multiplier
  if (lowerName.includes('multiplier')) {
    return {
      cdmPath: 'multiplier',
      transformation: 'map_multiplier',
      confidence: 85,
      reasoning: 'Multiplier field → CDM numeric multiplier',
      unitType: 'multiplier'
    }
  }

  // ========================================
  // NO MATCH
  // ========================================

  return {
    cdmPath: `unmapped.${input.fieldName}`,
    transformation: 'not_unit_field',
    confidence: 0,
    reasoning: `Field "${input.fieldName}" does not match unit/quantity/currency patterns.`,
    unitType: 'unknown'
  }
}
