// AUTO-GENERATED by Claude Code from FPML 5.12 + CDM 5.35.0 analysis
// Generation date: 2026-04-17

import { z } from 'zod'
import { BaseSkillInput, BaseSkillOutput } from '../types'

/**
 * Input schema for unit-normalizer
 */
export const UnitNormalizerInput = BaseSkillInput.extend({
  unit: z.string().optional(),              // Unit from schema (BBL, MT, MWh)
  currencyScheme: z.string().optional()     // Currency scheme if applicable
})

/**
 * Output schema for unit-normalizer
 */
export const UnitNormalizerOutput = BaseSkillOutput.extend({
  unitType: z.enum([
    'currency',
    'quantity',
    'notional',
    'amount',
    'price',
    'rate',
    'percentage',
    'multiplier',
    'unknown'
  ]),
  normalizedUnit: z.string().optional(),    // Normalized unit code (USD, BBL, etc.)
  cdmEnum: z.string().optional()             // CDM enum value if applicable
})

export type UnitNormalizerInput = z.infer<typeof UnitNormalizerInput>
export type UnitNormalizerOutput = z.infer<typeof UnitNormalizerOutput>
